bx bx-color
bx bx-reflect-horizontal
bx bx-reflect-vertical
bx bx-cart-add
bx bx-cart-download
bx bx-no-signal
bx bx-signal-5
bx bx-signal-4
bx bx-signal-3
bx bx-signal-2
bx bx-signal-1
bx bx-cheese
bx bx-hard-hat
bx bx-home-alt-2
bx bx-lemon
bx bx-cable-car
bx bx-cricket-ball
bx bx-male-female
bx bx-baguette
bx bx-fork
bx bx-knife
bx bx-circle-half
bx bx-circle-three-quarter
bx bx-circle-quarter
bx bx-bowl-rice
bx bx-bowl-hot
bx bx-popsicle
bx bx-cross
bx bx-scatter-chart
bx bx-money-withdraw
bx bx-candles
bx bx-math
bx bx-party
bx bx-leaf
bx bx-injection
bx bx-expand-vertical
bx bx-expand-horizontal
bx bx-collapse-vertical
bx bx-collapse-horizontal
bx bx-collapse-alt
bx bx-qr
bx bx-qr-scan
bx bx-podcast
bx bx-checkbox-minus
bx bx-speaker
bx bx-registered
bx bx-phone-off
bx bx-buildings
bx bx-store-alt
bx bx-bar-chart-alt-2
bx bx-message-dots
bx bx-message-rounded-dots
bx bx-memory-card
bx bx-wallet-alt
bx bx-slideshow
bx bx-message-square
bx bx-message-square-dots
bx bx-book-content
bx bx-chat
bx bx-edit-alt
bx bx-mouse-alt
bx bx-bug-alt
bx bx-notepad
bx bx-video-recording
bx bx-shape-square
bx bx-shape-triangle
bx bx-ghost
bx bx-mail-send
bx bx-code-alt
bx bx-grid
bx bx-user-pin
bx bx-run
bx bx-copy-alt
bx bx-transfer-alt
bx bx-book-open
bx bx-landscape
bx bx-comment
bx bx-comment-dots
bx bx-pyramid
bx bx-cylinder
bx bx-lock-alt
bx bx-lock-open-alt
bx bx-left-arrow-alt
bx bx-right-arrow-alt
bx bx-up-arrow-alt
bx bx-down-arrow-alt
bx bx-shape-circle
bx bx-cycling
bx bx-dna
bx bx-bowling-ball
bx bx-search-alt-2
bx bx-plus-medical
bx bx-street-view
bx bx-droplet
bx bx-paint-roll
bx bx-shield-alt-2
bx bx-error-alt
bx bx-square
bx bx-square-rounded
bx bx-polygon
bx bx-cube-alt
bx bx-cuboid
bx bx-user-voice
bx bx-accessibility
bx bx-building-house
bx bx-doughnut-chart
bx bx-log-in-circle
bx bx-log-out-circle
bx bx-check-square
bx bx-message-alt
bx bx-message-alt-dots
bx bx-no-entry
bx bx-palette
bx bx-basket
bx bx-purchase-tag-alt
bx bx-receipt
bx bx-line-chart
bx bx-map-pin
bx bx-hive
bx bx-band-aid
bx bx-credit-card-alt
bx bx-wifi-off
bx bx-brightness-half
bx bx-brightness
bx bx-filter-alt
bx bx-dialpad-alt
bx bx-border-right
bx bx-border-left
bx bx-border-top
bx bx-border-bottom
bx bx-border-all
bx bx-mobile-landscape
bx bx-mobile-vibration
bx bx-gas-pump
bx bx-pie-chart-alt-2
bx bx-time-five
bx bx-briefcase-alt-2
bx bx-brush-alt
bx bx-customize
bx bx-radio
bx bx-printer
bx bx-sort-a-z
bx bx-sort-z-a
bx bx-conversation
bx bx-exit
bx bx-extension
bx bx-face
bx bx-file-find
bx bx-label
bx bx-check-shield
bx bx-border-radius
bx bx-add-to-queue
bx bx-archive-in
bx bx-archive-out
bx bx-alarm-add
bx bx-space-bar
bx bx-image-alt
bx bx-image-add
bx bx-fridge
bx bx-dish
bx bx-spa
bx bx-cake
bx bx-bolt-circle
bx bx-tone
bx bx-bitcoin
bx bx-lira
bx bx-ruble
bx bx-rupee
bx bx-euro
bx bx-pound
bx bx-won
bx bx-yen
bx bx-shekel
bx bx-health
bx bx-clinic
bx bx-male
bx bx-female
bx bx-male-sign
bx bx-female-sign
bx bx-food-tag
bx bx-food-menu
bx bx-meh-alt
bx bx-wink-tongue
bx bx-happy-alt
bx bx-cool
bx bx-tired
bx bx-smile
bx bx-angry
bx bx-happy-heart-eyes
bx bx-dizzy
bx bx-wink-smile
bx bx-confused
bx bx-sleepy
bx bx-shocked
bx bx-happy-beaming
bx bx-meh-blank
bx bx-laugh
bx bx-upside-down
bx bx-diamond
bx bx-align-left
bx bx-align-middle
bx bx-align-right
bx bx-arrow-back
bx bx-bell-minus
bx bx-bell-off
bx bx-bell-plus
bx bx-bell
bx bx-bookmark
bx bx-bookmarks
bx bx-bullseye
bx bx-camera-off
bx bx-camera
bx bx-captions
bx bx-checkbox-checked
bx bx-checkbox
bx bx-checkbox-square
bx bx-chevron-down
bx bx-chevron-up
bx bx-chevron-left
bx bx-chevron-right
bx bx-chevrons-down
bx bx-chevrons-up
bx bx-chevrons-right
bx bx-chevrons-left
bx bx-clipboard
bx bx-code-curly
bx bx-code
bx bx-coffee
bx bx-copy
bx bx-copyright
bx bx-down-arrow-circle
bx bx-error-circle
bx bx-error
bx bx-exit-fullscreen
bx bx-fast-forward-circle
bx bx-fast-forward
bx bx-first-page
bx bx-folder-minus
bx bx-folder-plus
bx bx-folder
bx bx-fullscreen
bx bx-hide
bx bx-image
bx bx-info-circle
bx bx-align-justify
bx bx-key
bx bx-last-page
bx bx-left-arrow-circle
bx bx-left-down-arrow-circle
bx bx-left-indent
bx bx-left-top-arrow-circle
bx bx-menu
bx bx-microphone
bx bx-minus-circle
bx bx-moon
bx bx-pause-circle
bx bx-pause
bx bx-play-circle
bx bx-play
bx bx-plus-circle
bx bx-question-mark
bx bx-radio-circle-marked
bx bx-radio-circle
bx bx-rectangle
bx bx-rewind
bx bx-reset
bx bx-right-arrow-circle
bx bx-right-down-arrow-circle
bx bx-right-indent
bx bx-right-top-arrow-circle
bx bx-rss
bx bx-search
bx bx-show
bx bx-skip-next
bx bx-skip-previous
bx bx-stop-circle
bx bx-stop
bx bx-stopwatch
bx bx-sync
bx bx-time
bx bx-toggle-left
bx bx-toggle-right
bx bx-trending-down
bx bx-trending-up
bx bx-up-arrow-circle
bx bx-vertical-center
bx bx-video
bx bx-volume-full
bx bx-volume-low
bx bx-volume-mute
bx bx-volume
bx bx-x-circle
bx bx-zoom-in
bx bx-zoom-out
bx bx-archive
bx bx-at
bx bx-bar-chart-alt
bx bx-bar-chart-square
bx bx-bar-chart
bx bx-basketball
bx bx-block
bx bx-book-bookmark
bx bx-book
bx bx-bookmark-minus
bx bx-bookmark-plus
bx bx-briefcase
bx bx-broadcast
bx bx-building
bx bx-bug
bx bx-bluetooth
bx bx-bulb
bx bx-buoy
bx bx-calendar-plus
bx bx-calendar-check
bx bx-calendar-minus
bx bx-calendar-x
bx bx-calendar
bx bx-chart
bx bx-cloud-download
bx bx-cloud-upload
bx bx-cloud
bx bx-terminal
bx bx-crosshair
bx bx-compass
bx bx-data
bx bx-desktop
bx bx-directions
bx bx-dollar
bx bx-dots-horizontal-rounded
bx bx-dots-horizontal
bx bx-dots-vertical-rounded
bx bx-dots-vertical
bx bx-download
bx bx-envelope
bx bx-gift
bx bx-globe
bx bx-devices
bx bx-headphone
bx bx-heart
bx bx-home
bx bx-laptop
bx bx-layer
bx bx-link-alt
bx bx-link
bx bx-list-plus
bx bx-list-ul
bx bx-list-minus
bx bx-lock-open
bx bx-lock
bx bx-map-alt
bx bx-map
bx bx-message-rounded
bx bx-message
bx bx-mobile-alt
bx bx-mobile
bx bx-navigation
bx bx-phone
bx bx-pie-chart
bx bx-send
bx bx-sidebar
bx bx-sitemap
bx bx-spreadsheet
bx bx-tab
bx bx-tag
bx bx-target-lock
bx bx-tennis-ball
bx bx-alarm
bx bx-upload
bx bx-usb
bx bx-video-off
bx bx-voicemail
bx bx-wifi
bx bx-window-open
bx bx-window
bx bx-windows
bx bx-duplicate
bx bx-table
bx bx-x
bx bx-adjust
bx bx-album
bx bx-anchor
bx bx-award
bx bx-bold
bx bx-calculator
bx bx-cart
bx bx-check
bx bx-cloud-drizzle
bx bx-cloud-light-rain
bx bx-cloud-lightning
bx bx-cloud-rain
bx bx-cloud-snow
bx bx-cog
bx bx-columns
bx bx-credit-card
bx bx-crop
bx bx-cube
bx bx-cut
bx bx-detail
bx bx-shield-quarter
bx bx-edit
bx bx-file
bx bx-filter
bx bx-font
bx bx-git-branch
bx bx-git-commit
bx bx-git-compare
bx bx-git-merge
bx bx-git-pull-request
bx bx-git-repo-forked
bx bx-group
bx bx-hash
bx bx-heading
bx bx-home-alt
bx bx-italic
bx bx-joystick
bx bx-link-external
bx bx-log-in
bx bx-log-out
bx bx-microphone-off
bx bx-minus
bx bx-mouse
bx bx-move
bx bx-music
bx bx-notification
bx bx-package
bx bx-paragraph
bx bx-paste
bx bx-pencil
bx bx-pin
bx bx-plus
bx bx-power-off
bx bx-pulse
bx bx-save
bx bx-screenshot
bx bx-select-multiple
bx bx-share-alt
bx bx-share
bx bx-shield-alt
bx bx-shield
bx bx-shopping-bag
bx bx-shuffle
bx bx-sort
bx bx-star
bx bx-sun
bx bx-text
bx bx-trash
bx bx-trophy
bx bx-underline
bx bx-user-check
bx bx-user-circle
bx bx-user-minus
bx bx-user-plus
bx bx-user-x
bx bx-user
bx bx-barcode
bx bx-crown
bx bx-dislike
bx bx-down-arrow
bx bx-export
bx bx-first-aid
bx bx-flag
bx bx-history
bx bx-joystick-alt
bx bx-left-arrow
bx bx-like
bx bx-list-check
bx bx-poll
bx bx-radar
bx bx-redo
bx bx-reply-all
bx bx-reply
bx bx-repost
bx bx-revision
bx bx-right-arrow
bx bx-subdirectory-left
bx bx-subdirectory-right
bx bx-support
bx bx-timer
bx bx-undo
bx bx-up-arrow
bx bx-phone-call
bx bx-aperture
bx bx-film
bx bx-folder-open
bx bx-task
bx bx-server
bx bx-battery
bx bx-calendar-alt
bx bx-import
bx bx-ruler
bx bx-horizontal-center
bx bx-rotate-right
bx bx-rename
bx bx-collapse
bx bx-phone-incoming
bx bx-phone-outgoing
bx bx-body
bx bx-cast
bx bx-chip
bx bx-skip-next-circle
bx bx-skip-previous-circle
bx bx-hdd
bx bx-store
bx bx-globe-alt
bx bx-upvote
bx bx-downvote
bx bx-news
bx bx-pie-chart-alt
bx bx-images
bx bx-purchase-tag
bx bx-pen
bx bx-expand
bx bx-paperclip
bx bx-closet
bx bx-tv
bx bx-collection
bx bx-station
bx bx-wallet
bx bx-briefcase-alt
bx bx-hourglass
bx bx-carousel
bx bx-infinite
bx bx-plug
bx bx-notification-off
bx bx-window-close
bx bx-command
bx bx-grid-alt
bx bx-trash-alt
bx bx-chalkboard
bx bx-loader
bx bx-slider
bx bx-paper-plane
bx bx-selection
bx bx-world
bx bx-dock-bottom
bx bx-dock-right
bx bx-dock-top
bx bx-dock-left
bx bx-layout
bx bx-alarm-off
bx bx-wrench
bx bx-loader-circle
bx bx-loader-alt
bx bx-car
bx bx-cart-alt
bx bx-happy
bx bx-meh
bx bx-sad
bx bx-slider-alt
bx bx-certification
bx bx-rocket
bx bx-check-circle
bx bx-bus
bx bx-check-double
bx bx-dumbbell
bx bx-bot
bx bx-area
bx bx-bed
bx bx-bath
bx bx-train
bx bx-taxi
bx bx-movie
bx bx-hotel
bx bx-planet
bx bx-list-ol
bx bx-video-plus
bx bx-menu-alt-left
bx bx-menu-alt-right
bx bx-box
bx bx-restaurant
bx bx-swim
bx bx-water
bx bx-wind
bx bx-dialpad
bx bx-handicap
bx bx-font-size
bx bx-code-block
bx bx-photo-album
bx bx-strikethrough
bx bx-file-blank
bx bx-highlight
bx bx-font-color
bx bx-fingerprint
bx bx-transfer
bx bx-circle
bx bx-ball
bx bx-football
bx bx-dollar-circle
bx bx-search-alt
bx bx-analyse
bx bx-disc
bx bx-equalizer
bx bx-stats
bx bx-move-horizontal
bx bx-move-vertical
bx bx-grid-horizontal
bx bx-grid-vertical
bx bx-grid-small
bx bx-badge
bx bx-id-card
bx bx-sort-up
bx bx-sort-down
bx bx-note
bx bx-test-tube
bx bx-help-circle
bx bx-card
bx bx-rewind-circle
bx bx-magnet
bx bx-calendar-event
bx bx-caret-left
bx bx-caret-up
bx bx-caret-right
bx bx-caret-down
bx bx-show-alt
bx bx-badge-check
bx bx-rotate-left
bx bx-brush
bx bx-unlink
bx bx-paint
bx bx-joystick-button
bx bx-font-family
bx bx-repeat
bx bx-walk
bx bx-money
bx bx-home-circle
bx bx-location-plus
bx bx-arch
bx bx-atom
bx bx-baseball
bx bx-beer
bx bx-bible
bx bx-bomb
bx bx-bus-school
bx bx-cabinet
bx bx-calendar-edit
bx bx-coffee-togo
bx bx-pointer
bx bx-microchip
bx bx-heart-circle
bx bx-heart-square
bx bx-home-heart
bx bx-info-square
bx bx-layer-plus
bx bx-layer-minus
bx bx-recycle
bx bx-traffic-cone
bx bx-wifi-2
bx bx-wifi-1
bx bx-wifi-0
bx bx-mask
bx bx-low-vision
bx bx-been-here
bx bx-current-location
bx bx-arrow-from-top
bx bx-arrow-from-bottom
bx bx-arrow-from-left
bx bx-arrow-from-right
bx bx-arrow-to-right
bx bx-arrow-to-left
bx bx-arrow-to-top
bx bx-arrow-to-bottom
bx bx-book-reader
bx bx-scan
bx bx-calendar-week
bx bx-glasses
bx bx-glasses-alt
bx bx-border-none
bx bx-border-inner
bx bx-dice-1
bx bx-dice-2
bx bx-dice-3
bx bx-dice-4
bx bx-dice-5
bx bx-dice-6
bx bx-webcam
bx bx-spray-can
bx bx-sticker
bx bx-tachometer
bx bx-game
bx bx-abacus
bx bx-alarm-snooze
bx bx-alarm-exclamation
bx bx-medal
bx bx-task-x
bx bx-barcode-reader
bx bx-blanket
bx bx-bone
bx bx-bong
bx bx-book-alt
bx bx-book-heart
bx bx-book-add
bx bx-bracket
bx bx-brain
bx bx-border-outer
bx bx-braille
bx bx-window-alt
bx bx-calendar-heart
bx bx-wine
bx bx-vial
bx bx-color-fill
bx bx-capsule
bx bx-eraser
bx bx-drink
bx bx-cctv
bx bx-chair
bx bx-network-chart
bx bx-vector
bx bx-calendar-exclamation
bx bx-calendar-star
bx bx-camera-home
bx bx-camera-movie
bx bx-caret-right-circle
bx bx-caret-left-circle
bx bx-caret-up-circle
bx bx-caret-down-circle
bx bx-caret-right-square
bx bx-caret-up-square
bx bx-caret-left-square
bx bx-caret-down-square
bx bx-shield-x
bx bx-line-chart-down
bx bx-chevron-down-circle
bx bx-chevron-up-circle
bx bx-chevron-left-circle
bx bx-chevron-right-circle
bx bx-chevron-down-square
bx bx-chevron-up-square
bx bx-chevron-left-square
bx bx-chevron-right-square
bx bx-church
bx bx-coin
bx bx-coin-stack
bx bx-unite
bx bx-minus-front
bx bx-intersect
bx bx-exclude
bx bx-minus-back
bx bx-merge
bx bx-trim
bx bx-outline
bx bx-meteor
bx bx-refresh
bx bx-home-smile
bx bx-envelope-open
bx bx-message-alt-add
bx bx-message-alt-check
bx bx-message-alt-error
bx bx-message-alt-x
bx bx-message-alt-minus
bx bx-message-alt-edit
bx bx-message-alt-detail
bx bx-message-rounded-check
bx bx-message-rounded-error
bx bx-message-rounded-x
bx bx-message-rounded-minus
bx bx-message-rounded-edit
bx bx-message-rounded-add
bx bx-message-rounded-detail
bx bx-message-check
bx bx-message-error
bx bx-message-x
bx bx-message-minus
bx bx-message-edit
bx bx-message-add
bx bx-message-detail
bx bx-message-square-check
bx bx-message-square-error
bx bx-message-square-x
bx bx-message-square-minus
bx bx-message-square-edit
bx bx-message-square-add
bx bx-message-square-detail
bx bx-comment-check
bx bx-comment-error
bx bx-comment-x
bx bx-comment-edit
bx bx-comment-minus
bx bx-comment-add
bx bx-comment-detail
bx bx-cookie
bx bx-credit-card-front
bx bx-door-open
bx bx-donate-heart
bx bx-donate-blood
bx bx-shape-polygon
bx bx-bookmark-heart
bx bx-sort-alt-2
bx bx-category
bx bx-category-alt
bx bx-bookmark-alt
bx bx-bookmark-alt-plus
bx bx-bookmark-alt-minus
bx bx-tag-alt
bx bx-movie-play
bx bx-expand-alt
bx bx-library
bx bx-trip